"""initial schema

Revision ID: bb82bdc95bcc
Revises: 
Create Date: 2026-09-21 12:31:05.569383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb82bdc95bcc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batch_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='batch_status'), nullable=False),
    sa.Column('total_images', sa.Integer(), nullable=False),
    sa.Column('completed_images', sa.Integer(), nullable=False),
    sa.Column('failed_images', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('dataset_version', sa.String(length=32), nullable=False),
    sa.Column('weights_path', sa.String(length=512), nullable=False),
    sa.Column('run_dir', sa.String(length=512), nullable=False),
    sa.Column('hardware', sa.String(length=256), nullable=False),
    sa.Column('val_metrics', sa.JSON(), nullable=False),
    sa.Column('test_metrics', sa.JSON(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('is_production', sa.Boolean(), nullable=False),
    sa.Column('trained_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_versions_version'), 'model_versions', ['version'], unique=True)
    op.create_table('predictions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='prediction_status'), nullable=False),
    sa.Column('original_filename', sa.String(length=512), nullable=False),
    sa.Column('image_path', sa.String(length=512), nullable=False),
    sa.Column('annotated_image_path', sa.String(length=512), nullable=True),
    sa.Column('inference_time_ms', sa.Float(), nullable=True),
    sa.Column('error_message', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('model_version_id', sa.UUID(), nullable=True),
    sa.Column('batch_job_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['batch_job_id'], ['batch_jobs.id'], ),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_predictions_batch_job_id'), 'predictions', ['batch_job_id'], unique=False)
    op.create_index(op.f('ix_predictions_created_at'), 'predictions', ['created_at'], unique=False)
    op.create_table('detections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('prediction_id', sa.UUID(), nullable=False),
    sa.Column('class_name', sa.String(length=64), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('x_min', sa.Float(), nullable=False),
    sa.Column('y_min', sa.Float(), nullable=False),
    sa.Column('x_max', sa.Float(), nullable=False),
    sa.Column('y_max', sa.Float(), nullable=False),
    sa.Column('model_version', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detections_prediction_id'), 'detections', ['prediction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_detections_prediction_id'), table_name='detections')
    op.drop_table('detections')
    op.drop_index(op.f('ix_predictions_created_at'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_batch_job_id'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_model_versions_version'), table_name='model_versions')
    op.drop_table('model_versions')
    op.drop_table('batch_jobs')
    # ### end Alembic commands ###
